import Head from 'next/head';
import Header from '../components/Header';
import VideoCard from '../components/VideoCard';
import Pagination from '../components/Pagination';

import requests from "../utils/requests";
import { useState, useEffect } from 'react';


export default function Home({results}) {

  const [currentPage, setcurrentPage] = useState(1);
  const [postPerPage ] = useState(9);

  // Get current post:
  const indexOfLastPost = currentPage * postPerPage;
  const indexOfFirstPost = indexOfLastPost - postPerPage;
  const currentPost = results.slice(indexOfFirstPost, indexOfLastPost);

  // Change page
  const paginate = (pageNumber) => setcurrentPage(pageNumber);


  return (
    <div >
      <Head>
        <title>Movie Streamer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <VideoCard results={currentPost}/>
      <Pagination postPerPage={postPerPage} totalPosts={results.length} paginate={paginate}/>
      
    </div>
  )
}

export async function getServerSideProps(context) {

  const request = await fetch(
    `https://api.themoviedb.org/3/${
      requests.fetchMovies.url
    }`
  ).then(res => res.json());


  return {
    props: {
      results:request.results
    }
  }
}
